# src/prompts/__init__.py
"""提示词模块"""
from .safety_prompt import (
    SAFETY_SYSTEM_PROMPT,
    CRISIS_INTERVENTION_PROMPT,
    CHAT_SAFETY_PROMPT,
    check_safety,
    detect_crisis
)
from .chat_prompt import (
    CHAT_SYSTEM_PROMPT,
    INTENT_DETECTION_PROMPT,
    INTENT_RESPONSE_TEMPLATES,
    INTENT_ROUTER_PROMPT,
    SLOT_FILLING_PROMPT,
    CONTEXT_BUILDING_PROMPT,
    RAG_PROMPT,
    FLOW_CONTROL_PROMPT,
    STATE_MANAGEMENT_PROMPT,
    CONVERSATION_END_PROMPT,
    QUALITY_ASSESSMENT_PROMPT
)

__all__ = [
    # 安全提示词
    "SAFETY_SYSTEM_PROMPT",
    "CRISIS_INTERVENTION_PROMPT",
    "CHAT_SAFETY_PROMPT",
    "check_safety",
    "detect_crisis",
    # 多轮对话提示词
    "CHAT_SYSTEM_PROMPT",
    "INTENT_DETECTION_PROMPT",
    "INTENT_RESPONSE_TEMPLATES",
    "INTENT_ROUTER_PROMPT",
    "SLOT_FILLING_PROMPT",
    "CONTEXT_BUILDING_PROMPT",
    "RAG_PROMPT",
    "FLOW_CONTROL_PROMPT",
    "STATE_MANAGEMENT_PROMPT",
    "CONVERSATION_END_PROMPT",
    "QUALITY_ASSESSMENT_PROMPT"
]